services:
  - type: web
    name: banking-backend-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_2fn3ecHTjFkN@ep-long-grass-amjlgvmu.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
